name: Build and Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:


jobs:
  test:
    strategy:
      matrix:
        os: [windows-2022, windows-2019]
    name: Test against ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: CMake configure
        run: cmake -S . -B build -DGOERROR_BUILD_DOCS=OFF

      - name: Run Tests
        run: cmake --build build --target all-tests 
