name: Build and Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:


jobs:
  test:
    name: Test ${{ strategy.matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019]
    steps:
      - uses: actions/checkout@v3

      - name: CMake configure
        run: cmake -S . -B build

      - name: Run Tests
        run: cmake --build build --target all-tests 
